name: CD
on:
  push:
    branches:
      - master
      - develop # TODO: あとでけす
  pull_request:
    branches:
      - master
      - develop # TODO: あとでけす
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
permissions: {}
jobs:
  install:
    strategy:
      matrix:
        one: ["www", "api"]
        two: ["jp", "root"]
        three: ["com", "net", "app", "org"]
        four: ["public", "maintenance", "errors", "functions"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Sync to S3 (staging)
        if: false
        run: aws s3 sync ./src/${{ matrix.one }}/${{ matrix.two }}/${{ matrix.three }}/${{ matrix.four }} s3://umaxica.staging.cloudfront.${{ matrix.one }}.${{ matrix.two }}.${{ matrix.three }}.${{ matrix.four }} --delete
      - name: Sync to S3 (production)
        if: true
        run: aws s3 sync ./src/${{ matrix.one }}/${{ matrix.two }}/${{ matrix.three }}/${{ matrix.four }} s3://umaxica.production.cloudfront.${{ matrix.one }}.${{ matrix.two }}.${{ matrix.three }}.${{ matrix.four }} --delete
